"""rename given_name/family_name, drop username/picture/email_verified

Revision ID: 974dbc0404cc
Revises: be1f75588217
Create Date: 2026-05-12 18:41:36.354216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974dbc0404cc'
down_revision: Union[str, Sequence[str], None] = 'be1f75588217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'username')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
